# SwiftLint configuration for swift-iso-15924
# Inherits from the shared parent configuration in swift-standards

parent_config: https://raw.githubusercontent.com/swift-standards/swift-standards/main/.swiftlint.yml

# Package-specific overrides (if needed)
# Add any swift-iso-15924 specific rules here
